import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer/Footer";
import Nav from "./components/Nav/Nav";
import AOS from 'aos';
import 'aos/dist/aos.css'; // You can also use <link> for styles



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Farees Construction LImited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
